---
- hosts: local
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy custom index page
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Hello from OpenTofu</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 3rem; }
              h1 { color: #2d70c9; }
            </style>
          </head>
          <body>
            <h1>Hello, OpenTofu!</h1>
            <p>This page is served from bobobox-web-server-1 provisioned via OpenTofu and configured with Ansible.</p>
          </body>
          </html>
